# Inject All Secret Values into a Pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-3
  name: webapp-3
  namespace: default
spec:
  containers:
    - image: nginx
      name: webapp
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret

---
# Inject only a Single Secret Value into a Pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-4
  name: webapp-4
  namespace: default
spec:
  containers:
    - name: webapp-pod
      image: nginx
      ports:
        - containerPort: 8080
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
