apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  initContainers:
    - name: init-container
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo IP Address of Pod: $MY_POD_IP > /pod-content/index.txt",
        ]
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: pod-info
          mountPath: /pod-content
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: pod-info
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pod-info
      emptyDir: {}
