apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels: null
  app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:0.10.0"
          args:
            - "-nginx.scrape-uri=http://localhost/nginx_status"
          ports:
            - containerPort: 9113
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: nginx-config
          configMap:
            defaultMode: 420
            name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
