apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args:
        [
          "seq 1 30 | xargs -I{} echo 'sending...: {}' > /var/log/nginx/example.log && sleep 30",
        ]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
  volumes:
    - name: shared-logs
      emptyDir: {}
