apiVersion: v1
kind: Pod
metadata:
  name: level1
  labels:
    level: "1"
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: level2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: level
                operator: In
                values:
                  - "1"
          topologyKey: kubernetes.io/hostname
  containers:
    - name: pod-anti-affinity
      image: nginx
  tolerations:
    - key: color
      value: blue
      effect: NoSchedule
      operator: Equal
