apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
  tolerations:
    - key: color
      value: blue
      effect: NoSchedule
      operator: Equal
