apiVersion: apps/v1
kind: Deployment
metadata:
  name: lively-deploy
  labels:
    probe: lively-cmd
spec:
  replicas: 2
  selector:
    matchLabels:
      probe: lively-cmd
  template:
    metadata:
      labels:
        probe: lively-cmd
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
          livelienessProbe:
            exec:
              command:
                - cat
                - /usr/share/nginx/html/index.html
            initialDelaySeconds: 5
            periodSeconds: 5
